export const beats = [
  {
    id: 'beat1',
    title: '𝑆𝑡𝑖𝑙𝑙',
    artist: 'Neofantasia',
    genre: 'Trap',
    bpm: 140,
    price: 29.99,
    audioSrc: '/sfx/beats/still.wav',
    artwork: '/artwork/artw1.png',
  },
  {
    id: 'beat2',
    title: '𝑆ℎ𝑟𝑖𝑛𝑒',
    artist: 'Neofantasia',
    genre: 'Lo-Fi',
    bpm: 80,
    price: 29.99,
    audioSrc: '/sfx/shrine.mp3',
    artwork: '/artwork/ffx1.gif',
  },
  {
    id: 'beat3',
    title: '𝑆𝑢𝑚𝑚𝑒𝑟𝑠 𝐺𝑜𝑛𝑒',
    artist: 'Neofantasia',
    genre: 'Pop',
    bpm: 128,
    price: 29.99,
    audioSrc: '/sfx/summersgone.wav',
    artwork: '/artwork/artw1.png',
  },
  {
    id: 'beat4',
    title: '𝑆𝑢𝑚𝑚𝑒𝑟𝑠 𝐺𝑜𝑛𝑒',
    artist: 'Neofantasia',
    genre: 'Ambient',
    bpm: 100,
    price: 29.99,
    audioSrc: '/sfx/beats/summersgone.wav',
    artwork: '/artwork/artw1.png',
  }
];