export const beats = [
  {
    id: 'beat1',
    title: '𝑆𝑡𝑖𝑙𝑙',
    artist: 'neofantasia',
    genre: 'Trap',
    bpm: 140,
    price: 29.99,
    audioSrc: '/sfx/still.mp3',
    artwork: '/artwork/artw1.png',
  },
  {
    id: 'beat2',
    title: '𝑆ℎ𝑟𝑖𝑛𝑒',
    artist: 'neofantasia',
    genre: 'Lo-Fi',
    bpm: 80,
    price: 29.99,
    audioSrc: '/sfx/shrine.mp3',
    artwork: '/artwork/ffx1.gif',
  },
    {
    id: 'beat3',
    title: '𝑆𝑢𝑚𝑚𝑒𝑟𝑠 𝐺𝑜𝑛𝑒',
    artist: 'neofantasia',
    genre: 'Lo-Fi',
    bpm: 80,
    price: 29.99,
    audioSrc: '/sfx/summersgone.wav',
    artwork: '/artwork/ffx1.gif',
  },
    {
    id: 'beat4',
    title: '𝐴𝑛𝑔𝑒𝑙 𝑊𝑖𝑛𝑔𝑠',
    artist: 'neofantasia',
    genre: 'Lo-Fi',
    bpm: 80,
    price: 29.99,
    audioSrc: '/sfx/angelwings.wav',
    artwork: '/artwork/ffx1.gif',
  },
  {
    id: 'beat5',
    title: '𝑅𝑒𝑣𝑒𝑟𝑖𝑒',
    artist: 'Neofantasia',
    genre: 'Pop',
    bpm: 128,
    price: 29.99,
    audioSrc: '/sfx/reverie.wav',
    artwork: '/artwork/artw1.png',
  },
  {
    id: 'beat6',
    title: '𝑆𝑢𝑚𝑚𝑒𝑟𝑠 𝐺𝑜𝑛𝑒',
    artist: 'Neofantasia',
    genre: 'Ambient',
    bpm: 100,
    price: 29.99,
    audioSrc: '/sfx/beats/summersgone.wav',
    artwork: '/artwork/artw1.png',
  }
];